fix genesis exporting of tendermint metadata
cosmos/ibc-go pull request #210
Opened 2021-06-03 11:55 UTC by colin-axner

## Description

closes: #191 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2021-06-03 11:57 UTC, colin-axner commented on CHANGELOG.md
> +* (07-tendermint) [#\210](https://github.com/cosmos/ibc-go/pull/210) Correctly exported consensus metadata on genesis restarts for tendermint clients.
```suggestion
* (07-tendermint) [#\210](https://github.com/cosmos/ibc-go/pull/210) Exporte all consensus metadata on genesis restarts for tendermint clients.
```

2021-06-03 11:58 UTC, colin-axner commented on modules/light-clients/07-tendermint/types/genesis_test.go
>  func (suite *TendermintTestSuite) TestExportMetadata() {
This test could be better using a for loop for the updates, but it doesn't feel worth the effort. I think this covers the necessary purposes

2021-06-07 19:30 UTC, AdityaSripal requested changes
This solution does not work for iteration keys

2021-06-07 19:30 UTC, AdityaSripal commented on modules/light-clients/07-tendermint/types/store.go
> +		if len(keySplit) != 3 {
This will not work since the iteration keys have a completely different format

2021-06-07 19:31 UTC, AdityaSripal approved these changes

2021-06-07 19:31 UTC, AdityaSripal commented on modules/light-clients/07-tendermint/types/store.go
> +	for ; iterator.Valid(); iterator.Next() {
Ahh I see this, good work!

2021-06-08 11:25 UTC, merged