chore: update godocs for legacy apis on controller module
cosmos/ibc-go pull request #2363
Opened 2022-09-21 15:39 UTC by charleenfei

## Description

closes: #2234 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2022-09-23 12:11 UTC, chatton approved these changes
LGTM 🥇 thanks for fixing typo!

2022-09-26 13:19 UTC, damiannolan approved these changes
LGTM! 🚀

2022-09-26 13:19 UTC, damiannolan commented on modules/apps/27-interchain-accounts/controller/keeper/account.go
> +// by the underlying authentication application. For a full summary of the changes in v6.x.x, please see ADR009.
nit

```suggestion
// NOTE: this is a legacy API that is only intended to function correctly in workflows where an underlying application has been set.
// Prior to to v6.x.x of ibc-go, the controller module was only functional as middleware, with authentication performed
// by the underlying application. For a full summary of the changes in v6.x.x, please see ADR009.
```

2022-09-26 13:19 UTC, damiannolan commented on modules/apps/27-interchain-accounts/controller/keeper/relay.go
> +// by the underlying authentication application. For a full summary of the changes in v6.x.x, please see ADR009.
same nit

```suggestion
// NOTE: this is a legacy API that is only intended to function correctly in workflows where an underlying application has been set.
// Prior to to v6.x.x of ibc-go, the controller module was only functional as middleware, with authentication performed
// by the underlying application. For a full summary of the changes in v6.x.x, please see ADR009.
```

2022-09-26 16:05 UTC, colin-axner commented on modules/apps/27-interchain-accounts/controller/keeper/account.go
> +// NOTE: this is a legacy API that is only intended to function correctly in workflows where an underlying application has been set
```suggestion
// NOTE: this is a legacy API that is only intended to function correctly in workflows where an underlying application has been set. Calling this API will result in all packet callbacks being routed to the underlying application.
// Please use MsgRegisterInterchainAccount for use cases which do not need to route to an underlying application
```

2022-09-30 09:13 UTC, damiannolan requested changes
@charleenfei could you pull in the changes from #2448 here please? See https://github.com/cosmos/ibc-go/pull/2448#issuecomment-1263304151

Thanks!

2022-10-13 18:46 UTC, damiannolan approved these changes
🙏

2022-10-14 10:48 UTC, colin-axner approved these changes

2022-10-14 12:17 UTC, merged