scaffolding for 29-fee
cosmos/ibc-go pull request #274
Opened 2021-07-20 14:18 UTC by colin-axner

## Description

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2021-07-20 14:30 UTC, AdityaSripal requested changes
uncomment code files and remove test files

2021-07-20 14:30 UTC, AdityaSripal commented on modules/apps/29-fee/keeper/genesis.go
> +
uncomment

2021-07-20 14:30 UTC, AdityaSripal commented on modules/apps/29-fee/keeper/grpc_query.go
> +// TODO
uncomment

2021-07-20 14:30 UTC, AdityaSripal commented on modules/apps/29-fee/keeper/keeper.go
> +/*
uncomment

2021-07-20 14:30 UTC, AdityaSripal commented on modules/apps/29-fee/keeper/keeper_test.go
> +/*
uncomment

2021-07-20 14:30 UTC, AdityaSripal commented on modules/apps/29-fee/keeper/msg_server.go
> +//var _ types.MsgServer = Keeper{}
uncomment

2021-07-20 14:30 UTC, AdityaSripal commented on modules/apps/29-fee/module_test.go
> +package fee_test
Remove this file since it will be very customized

2021-07-21 08:50 UTC, seantking approved these changes

2021-07-21 09:42 UTC, AdityaSripal approved these changes

2021-07-21 09:43 UTC, merged