upgrade to go 1.20 and newer protobuf builder to reduce v50 changeset
cosmos/ibc-go pull request #3811
Opened 2023-06-10 07:36 UTC by faddat

This PR uses go 1.20 and the latest protobuf builder so that the changeset for 
v50 is smaller.  This is the same intent as the earlier thelper PR, basically to 
reduce the total number of changes that will be present in the v50 pr.

2023-06-11 21:17 UTC, crodriguezvega requested changes
Thank you, @faddat! I think it would be nice to take out the bump to SDK v0.47.3 out of this PR (since you have that covered in #3810) and then the scope of this PR will very nicely be scope to bumping go version and protobuf builder version. :)

If these are changes required for SDK v0.50. Should we target this PR to the [feature branch](https://github.com/cosmos/ibc-go/tree/feat/upgrade-sdk-v0.50)?

2023-06-12 04:56 UTC, faddat commented
Hey Carlos, I'm very happy to do that. I will take care of that right now.

2023-06-12 04:58 UTC, faddat commented
...btw I do have a question -- I could not really figure out why the capabilities module does not build here, do you have any ideas?

2023-06-12 07:19 UTC, crodriguezvega commented
> I could not really figure out why the capabilities module does not build here, do you have any ideas?

Looks like it's building now, right?

2023-06-12 07:34 UTC, crodriguezvega approved these changes
Looks good; thank you, @faddat!

2023-06-12 08:34 UTC, damiannolan approved these changes
Thanks @faddat, lgtm!

2023-06-12 08:34 UTC, damiannolan commented on .github/workflows/capability.yml
> +          go-version: "1.20"
apparently they [recommend single quotes](https://github.com/actions/setup-go#v3) due to some yaml parsing but I don't think it'll make too much of a difference

2023-06-12 10:50 UTC, DimitrisJim reviewed
:rocket:

2023-06-12 10:50 UTC, DimitrisJim approved these changes

2023-06-12 13:32 UTC, faddat commented
I'll make it single quotes because following the recommendations is great :)

2023-06-12 16:00 UTC, colin-axner commented
Was this commit https://github.com/cosmos/ibc-go/pull/3811/commits/dd3b04b51dc7b8cb700cfdf7c41fcd4bb05d8c10 supposed to turn the quotes into single quotes or is the intention to do it in a followup commit?

2023-06-12 18:50 UTC, faddat commented
Hey Colin, yeah that was definitely supposed to be single quotes and I think that I should just revert that commit, I'm not sure how it ended up that way

2023-06-12 19:03 UTC, faddat commented
So what ended up being necessary was just reconfiguring my editor to use single quotes in YAML by default. 

When I did the flub commit before, it was because my editor was changing the singles to doubles when I saved the file.

2023-06-13 10:35 UTC, colin-axner approved these changes

2023-06-13 11:12 UTC, merged