docs: developing ica auth module
cosmos/ibc-go pull request #633
Opened 2021-12-15 10:42 UTC by colin-axner

## Description

ref: #512 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2021-12-15 13:39 UTC, damiannolan approved these changes
Nice work 👍 
I think it may be useful to reference ICS-30 or link to the middleware docs somewhere at the beginning of the doc

2021-12-15 13:39 UTC, damiannolan commented on docs/app_modules/interchain-accounts/ica_auth.md
> +# Building an ICA Authentication Module
Should we maybe link to or reference ICS-30 in this intro section?

2021-12-15 13:39 UTC, damiannolan commented on docs/app_modules/interchain-accounts/ica_auth.md
> +There may exist may different types of authentication which are desirable for different use cases.
```suggestion
There may exist many different types of authentication which are desirable for different use cases. 
```

2021-12-15 13:39 UTC, damiannolan commented on docs/app_modules/interchain-accounts/ica_auth.md
> +The authentication module must:
Should we add claiming of channel capability to this bulleted list? I know it is mentioned below but just a thought as I read through.

But maybe it's okay to omit(?) if this intended to be a higher level overview. Your call!

2021-12-15 15:00 UTC, crodriguezvega requested changes
Thanks for writing his docs, @colin-axner. Sorry that I got a bit too excited with the alignments... I think you should check them in the whole document, there are other places where they are off that I didn't comment on.

2021-12-17 12:45 UTC, colin-axner commented on docs/app_modules/interchain-accounts/ica_auth.md
> +### Integration into app.go file
Agreed, which format do we want to go with. 

Also in this document I only see the main title as having multiple words capitalized, but "Authentication Module" could arguably capitalized as the name of something. Should I change this?

2021-12-17 13:07 UTC, seantking approved these changes

2021-12-20 06:18 UTC, crodriguezvega commented on docs/app_modules/interchain-accounts/ica_auth.md
> +### Integration into app.go file
I would say let's go with capitalizing only the first word. And wrt to authentication module, I don't see a reason to capitalize it, so I would also leave it uncapitalized.

2021-12-20 06:19 UTC, crodriguezvega commented on docs/app_modules/interchain-accounts/ica_auth.md
> +### Integration into app.go file
```suggestion
### Integration into `app.go` file
```

2021-12-20 08:29 UTC, crodriguezvega approved these changes

2021-12-20 09:56 UTC, merged