chore: Add OnAcknowledgmentPacket to IBCModule V2 Interface
cosmos/ibc-go pull request #7438
Opened 2024-10-10 13:50 UTC by bznein

## Description

Somewhat forgot about this one!

closes: #7410

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against the correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to GitHub issue with discussion and accepted design, OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/build/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [conventional commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to follow the repository standards.
- [ ] Include a descriptive changelog entry when appropriate. This may be left to the discretion of the PR reviewers. (e.g. chores should be omitted from changelog)
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.
- [ ] Review `SonarCloud Report` in the comment section below once CI passes.

2024-10-10 13:51 UTC, bznein commented on testing/mock/v2/ibc_app.go
> +	OnAcknowledgementPacket func(ctx context.Context, sourceID string, destinationID string, data channeltypesv2.PacketData, acknowldgement []byte, relayer sdk.AccAddress) error
we could probably rename all `sourceID` and `destinationID` here but it can be done in a separate PR imho

2024-10-10 13:57 UTC, bznein commented on testing/mock/v2/ibc_app.go
> +	OnAcknowledgementPacket func(ctx context.Context, sourceID string, destinationID string, data channeltypesv2.PacketData, acknowldgement []byte, relayer sdk.AccAddress) error
Ah I think actually Cian did it in his PR. I will take care of merge conflicts

2024-10-14 10:29 UTC, damiannolan approved these changes
lgtm

2024-10-14 10:30 UTC, merged

2024-10-14 10:30 UTC, damiannolan requested changes
whoops

2024-10-14 10:30 UTC, damiannolan commented on modules/core/api/module.go
> +		destinationID string,
should be sourceChannel / destinationChannel

2024-10-14 10:30 UTC, damiannolan commented on testing/mock/v2/ibc_app.go
> +	OnAcknowledgementPacket func(ctx context.Context, sourceID string, destinationID string, data channeltypesv2.PacketData, acknowledgement []byte, relayer sdk.AccAddress) error
ditto

2024-10-14 10:30 UTC, damiannolan commented on testing/mock/v2/ibc_module.go
> +func (im IBCModule) OnAcknowledgementPacket(ctx context.Context, sourceID string, destinationID string, data channeltypesv2.PacketData, acknowledgement []byte, relayer sdk.AccAddress) error {
ditto!