chore(docs): delete not exist file path
cosmos/ibc-go pull request #7518
Opened 2024-10-25 21:40 UTC by odyslaeth

Hi there, the file is not exist. so I delete the path

2024-10-28 09:08 UTC, damiannolan requested changes
Hi thanks for the PR @odyslaeth! 

Given that this is versioned documentation, for previous release lines, it would be great if we could update the link to reflect the correct version. It looks like it previously was pointing to a feat branch. I've linked the correct code link in the PR.

Note this is only relevant to older release lines of ibc-go. As the localhost client is now stateless and does not require tracking updates via the BeginBlocker lifecycle handler.

2024-10-28 09:08 UTC, damiannolan commented on docs/versioned_docs/version-v7.8.x/03-light-clients/03-localhost/03-client-state.md
> -[See `BeginBlocker` in abci.go.](https://github.com/cosmos/ibc-go/blob/09-localhost/modules/core/02-client/abci.go#L12)
Can we change the link to https://github.com/cosmos/ibc-go/blob/v7.8.0/modules/core/02-client/abci.go#L12

2024-10-29 17:31 UTC, odyslaeth commented
NP Done thanks for the catching @damiannolan

2024-10-30 21:22 UTC, damiannolan approved these changes

2024-10-30 21:22 UTC, damiannolan commented
Thank you @odyslaeth!

2024-10-30 21:22 UTC, merged